# Dependencies
markdown:         redcarpet

redcarpet:
  extensions: ['strikethrough']

highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            pydass_vasp
description:      'Convenient Python modules and wrapping executable scripts.'
url:              http://terencezl.github.io
baseurl:          /pydass_vasp

author:
  name:           'Terence Zhi Liu'
  url:            http://terencezl.github.io

# Custom vars

github:
  repo:           https://github.com/terencezl/pydass_vasp
